subroutine cgbrfsx(trans,equed,n,kl,ku,nrhs,ab,ldab,afb,ldafb,ipiv,r,c,b,ldb,x,ldx,rcond,berr,n_err_bnds,err_bnds_norm,err_bnds_comp,nparams,params,work,rwork,info) CNAME(cgbrfsx)
import
character(len=1)::trans
character(len=1)::equed
integer(blas77_int)::n
integer(blas77_int)::kl
integer(blas77_int)::ku
integer(blas77_int)::nrhs
integer(blas77_int)::ldab
complex(blas77_f32)::ab(ldab,*)
integer(blas77_int)::ldafb
complex(blas77_f32)::afb(ldafb,*)
integer(blas77_int)::ipiv(*)
real(blas77_f32)::r(*)
real(blas77_f32)::c(*)
integer(blas77_int)::ldb
complex(blas77_f32)::b(ldb,*)
integer(blas77_int)::ldx
complex(blas77_f32)::x(ldx,*)
real(blas77_f32)::rcond
real(blas77_f32)::berr(*)
integer(blas77_int)::n_err_bnds
real(blas77_f32)::err_bnds_norm(nrhs,*)
real(blas77_f32)::err_bnds_comp(nrhs,*)
integer(blas77_int)::nparams
real(blas77_f32)::params(*)
complex(blas77_f32)::work(*)
real(blas77_f32)::rwork(*)
integer(blas77_int)::info
end
