subroutine cgedmd(jobs,jobz,jobr,jobf,whtsvd,m,n,x,ldx,y,ldy,nrnk,tol,k,eigs,z,ldz,res,b,ldb,w,ldw,s,lds,zwork,lzwork,rwork,lrwork,iwork,liwork,info) CNAME(cgedmd)
import
character(len=1),intent(in)::jobs
character(len=1),intent(in)::jobz
character(len=1),intent(in)::jobr
character(len=1),intent(in)::jobf
integer(blas77_int),intent(in)::whtsvd
integer(blas77_int),intent(in)::m
integer(blas77_int),intent(in)::n
integer(blas77_int),intent(in)::ldx
complex(blas77_f32),intent(inout)::x(ldx,*)
integer(blas77_int),intent(in)::ldy
complex(blas77_f32),intent(inout)::y(ldy,*)
integer(blas77_int),intent(in)::nrnk
real(blas77_f32),intent(in)::tol
integer(blas77_int),intent(out)::k
complex(blas77_f32),intent(out)::eigs(*)
integer(blas77_int),intent(in)::ldz
complex(blas77_f32),intent(out)::z(ldz,*)
real(blas77_f32),intent(out)::res(*)
integer(blas77_int),intent(in)::ldb
complex(blas77_f32),intent(out)::b(ldb,*)
integer(blas77_int),intent(in)::ldw
complex(blas77_f32),intent(out)::w(ldw,*)
integer(blas77_int),intent(in)::lds
complex(blas77_f32),intent(out)::s(lds,*)
complex(blas77_f32),intent(out)::zwork(*)
integer(blas77_int),intent(in)::lzwork
real(blas77_f32),intent(out)::rwork(*)
integer(blas77_int),intent(in)::lrwork
integer(blas77_int),intent(out)::iwork(*)
integer(blas77_int),intent(in)::liwork
integer(blas77_int),intent(out)::info
end
