subroutine cgedmdq(jobs,jobz,jobr,jobq,jobt,jobf,whtsvd,m,n,f,ldf,x,ldx,y,ldy,nrnk,tol,k,eigs,z,ldz,res,b,ldb,v,ldv,s,lds,zwork,lzwork,work,lwork,iwork,liwork,info) CNAME(cgedmdq)
import
character(len=1),intent(in)::jobs
character(len=1),intent(in)::jobz
character(len=1),intent(in)::jobr
character(len=1),intent(in)::jobq
character(len=1),intent(in)::jobt
character(len=1),intent(in)::jobf
integer(blas77_int),intent(in)::whtsvd
integer(blas77_int),intent(in)::m
integer(blas77_int),intent(in)::n
integer(blas77_int),intent(in)::ldf
complex(blas77_f32),intent(inout)::f(ldf,*)
integer(blas77_int),intent(in)::ldx
complex(blas77_f32),intent(out)::x(ldx,*)
integer(blas77_int),intent(in)::ldy
complex(blas77_f32),intent(out)::y(ldy,*)
integer(blas77_int),intent(in)::nrnk
real(blas77_f32),intent(in)::tol
integer(blas77_int),intent(out)::k
complex(blas77_f32),intent(out)::eigs(*)
integer(blas77_int),intent(in)::ldz
complex(blas77_f32),intent(out)::z(ldz,*)
real(blas77_f32),intent(out)::res(*)
integer(blas77_int),intent(in)::ldb
complex(blas77_f32),intent(out)::b(ldb,*)
integer(blas77_int),intent(in)::ldv
complex(blas77_f32),intent(out)::v(ldv,*)
integer(blas77_int),intent(in)::lds
complex(blas77_f32),intent(out)::s(lds,*)
complex(blas77_f32),intent(out)::zwork(*)
integer(blas77_int),intent(in)::lzwork
real(blas77_f32),intent(out)::work(*)
integer(blas77_int),intent(in)::lwork
integer(blas77_int),intent(out)::iwork(*)
integer(blas77_int),intent(in)::liwork
integer(blas77_int),intent(out)::info
end
