subroutine cgesvj(joba,jobu,jobv,m,n,a,lda,sva,mv,v,ldv,cwork,lwork,rwork,lrwork,info) CNAME(cgesvj)
import
character(len=1)::joba
character(len=1)::jobu
character(len=1)::jobv
integer(blas77_int)::m
integer(blas77_int)::n
integer(blas77_int)::lda
complex(blas77_f32)::a(lda,*)
real(blas77_f32)::sva(n)
integer(blas77_int)::mv
integer(blas77_int)::ldv
complex(blas77_f32)::v(ldv,*)
integer(blas77_int)::lwork
complex(blas77_f32)::cwork(lwork)
integer(blas77_int)::lrwork
real(blas77_f32)::rwork(lrwork)
integer(blas77_int)::info
end
