subroutine cggevx(balanc,jobvl,jobvr,sense,n,a,lda,b,ldb,alpha,beta,vl,ldvl,vr,ldvr,ilo,ihi,lscale,rscale,abnrm,bbnrm,rconde,rcondv,work,lwork,rwork,iwork,bwork,info) CNAME(cggevx)
import
character(len=1)::balanc
character(len=1)::jobvl
character(len=1)::jobvr
character(len=1)::sense
integer(blas77_int)::n
integer(blas77_int)::lda
complex(blas77_f32)::a(lda,*)
integer(blas77_int)::ldb
complex(blas77_f32)::b(ldb,*)
complex(blas77_f32)::alpha(*)
complex(blas77_f32)::beta(*)
integer(blas77_int)::ldvl
complex(blas77_f32)::vl(ldvl,*)
integer(blas77_int)::ldvr
complex(blas77_f32)::vr(ldvr,*)
integer(blas77_int)::ilo
integer(blas77_int)::ihi
real(blas77_f32)::lscale(*)
real(blas77_f32)::rscale(*)
real(blas77_f32)::abnrm
real(blas77_f32)::bbnrm
real(blas77_f32)::rconde(*)
real(blas77_f32)::rcondv(*)
complex(blas77_f32)::work(*)
integer(blas77_int)::lwork
real(blas77_f32)::rwork(*)
integer(blas77_int)::iwork(*)
logical::bwork(*)
integer(blas77_int)::info
end
