subroutine chpsvx(fact,uplo,n,nrhs,ap,afp,ipiv,b,ldb,x,ldx,rcond,ferr,berr,work,rwork,info) CNAME(chpsvx)
import
character(len=1)::fact
character(len=1)::uplo
integer(blas77_int)::n
integer(blas77_int)::nrhs
complex(blas77_f32)::ap(*)
complex(blas77_f32)::afp(*)
integer(blas77_int)::ipiv(*)
integer(blas77_int)::ldb
complex(blas77_f32)::b(ldb,*)
integer(blas77_int)::ldx
complex(blas77_f32)::x(ldx,*)
real(blas77_f32)::rcond
real(blas77_f32)::ferr(*)
real(blas77_f32)::berr(*)
complex(blas77_f32)::work(*)
real(blas77_f32)::rwork(*)
integer(blas77_int)::info
end
