subroutine cla_gbrfsx_extended(prec_type,trans_type,n,kl,ku,nrhs,ab,ldab,afb,ldafb,ipiv,colequ,c,b,ldb,y,ldy,berr_out,n_norms,err_bnds_norm,err_bnds_comp,res,ayb,dy,y_tail,rcond,ithresh,rthresh,dz_ub,ignore_cwise,info) CNAME(cla_gbrfsx_extended)
import
integer(blas77_int)::prec_type
integer(blas77_int)::trans_type
integer(blas77_int)::n
integer(blas77_int)::kl
integer(blas77_int)::ku
integer(blas77_int)::nrhs
integer(blas77_int)::ldab
complex(blas77_f32)::ab(ldab,*)
integer(blas77_int)::ldafb
complex(blas77_f32)::afb(ldafb,*)
integer(blas77_int)::ipiv(*)
logical::colequ
real(blas77_f32)::c(*)
integer(blas77_int)::ldb
complex(blas77_f32)::b(ldb,*)
integer(blas77_int)::ldy
complex(blas77_f32)::y(ldy,*)
real(blas77_f32)::berr_out(*)
integer(blas77_int)::n_norms
real(blas77_f32)::err_bnds_norm(nrhs,*)
real(blas77_f32)::err_bnds_comp(nrhs,*)
complex(blas77_f32)::res(*)
real(blas77_f32)::ayb(*)
complex(blas77_f32)::dy(*)
complex(blas77_f32)::y_tail(*)
real(blas77_f32)::rcond
integer(blas77_int)::ithresh
real(blas77_f32)::rthresh
real(blas77_f32)::dz_ub
logical::ignore_cwise
integer(blas77_int)::info
end
