subroutine clalsa(icompq,smlsiz,n,nrhs,b,ldb,bx,ldbx,u,ldu,vt,k,difl,difr,z,poles,givptr,givcol,ldgcol,perm,givnum,c,s,rwork,iwork,info) CNAME(clalsa)
import
integer(blas77_int)::icompq
integer(blas77_int)::smlsiz
integer(blas77_int)::n
integer(blas77_int)::nrhs
integer(blas77_int)::ldb
complex(blas77_f32)::b(ldb,*)
integer(blas77_int)::ldbx
complex(blas77_f32)::bx(ldbx,*)
integer(blas77_int)::ldu
real(blas77_f32)::u(ldu,*)
real(blas77_f32)::vt(ldu,*)
integer(blas77_int)::k(*)
real(blas77_f32)::difl(ldu,*)
real(blas77_f32)::difr(ldu,*)
real(blas77_f32)::z(ldu,*)
real(blas77_f32)::poles(ldu,*)
integer(blas77_int)::givptr(*)
integer(blas77_int)::ldgcol
integer(blas77_int)::givcol(ldgcol,*)
integer(blas77_int)::perm(ldgcol,*)
real(blas77_f32)::givnum(ldu,*)
real(blas77_f32)::c(*)
real(blas77_f32)::s(*)
real(blas77_f32)::rwork(*)
integer(blas77_int)::iwork(*)
integer(blas77_int)::info
end
