subroutine claqr2(wantt,wantz,n,ktop,kbot,nw,h,ldh,iloz,ihiz,z,ldz,ns,nd,sh,v,ldv,nh,t,ldt,nv,wv,ldwv,work,lwork) CNAME(claqr2)
import
logical(blas77_int)::wantt
logical(blas77_int)::wantz
integer(blas77_int)::n
integer(blas77_int)::ktop
integer(blas77_int)::kbot
integer(blas77_int)::nw
integer(blas77_int)::ldh
complex(blas77_f32)::h(ldh,*)
integer(blas77_int)::iloz
integer(blas77_int)::ihiz
integer(blas77_int)::ldz
complex(blas77_f32)::z(ldz,*)
integer(blas77_int)::ns
integer(blas77_int)::nd
complex(blas77_f32)::sh(*)
integer(blas77_int)::ldv
complex(blas77_f32)::v(ldv,*)
integer(blas77_int)::nh
integer(blas77_int)::ldt
complex(blas77_f32)::t(ldt,*)
integer(blas77_int)::nv
integer(blas77_int)::ldwv
complex(blas77_f32)::wv(ldwv,*)
complex(blas77_f32)::work(*)
integer(blas77_int)::lwork
end
