recursive subroutine claqz2(ilschur,ilq,ilz,n,ilo,ihi,nw,a,lda,b,ldb,q,ldq,z,ldz,ns,nd,alpha,beta,qc,ldqc,zc,ldzc,work,lwork,rwork,rec,info) CNAME(claqz2)
import
logical,intent(in)::ilschur
logical,intent(in)::ilq
logical,intent(in)::ilz
integer(blas77_int),intent(in)::n
integer(blas77_int),intent(in)::ilo
integer(blas77_int),intent(in)::ihi
integer(blas77_int),intent(in)::nw
integer(blas77_int),intent(in)::lda
complex(blas77_f32),intent(inout)::a(lda,*)
integer(blas77_int),intent(in)::ldb
complex(blas77_f32),intent(inout)::b(ldb,*)
integer(blas77_int),intent(in)::ldq
complex(blas77_f32),intent(inout)::q(ldq,*)
integer(blas77_int),intent(in)::ldz
complex(blas77_f32),intent(inout)::z(ldz,*)
integer(blas77_int),intent(out)::ns
integer(blas77_int),intent(out)::nd
complex(blas77_f32),intent(inout)::alpha(*)
complex(blas77_f32),intent(inout)::beta(*)
integer(blas77_int),intent(in)::ldqc
complex(blas77_f32)::qc(ldqc,*)
integer(blas77_int),intent(in)::ldzc
complex(blas77_f32)::zc(ldzc,*)
complex(blas77_f32)::work(*)
integer(blas77_int),intent(in)::lwork
real(blas77_f32)::rwork(*)
integer(blas77_int),intent(in)::rec
integer(blas77_int),intent(out)::info
end
