subroutine ctgsna(job,howmny,select,n,a,lda,b,ldb,vl,ldvl,vr,ldvr,s,dif,mm,m,work,lwork,iwork,info) CNAME(ctgsna)
import
character(len=1)::job
character(len=1)::howmny
logical::select(*)
integer(blas77_int)::n
integer(blas77_int)::lda
complex(blas77_f32)::a(lda,*)
integer(blas77_int)::ldb
complex(blas77_f32)::b(ldb,*)
integer(blas77_int)::ldvl
complex(blas77_f32)::vl(ldvl,*)
integer(blas77_int)::ldvr
complex(blas77_f32)::vr(ldvr,*)
real(blas77_f32)::s(*)
real(blas77_f32)::dif(*)
integer(blas77_int)::mm
integer(blas77_int)::m
complex(blas77_f32)::work(*)
integer(blas77_int)::lwork
integer(blas77_int)::iwork(*)
integer(blas77_int)::info
end
