subroutine ctgsja(jobu,jobv,jobq,m,p,n,k,l,a,lda,b,ldb,tola,tolb,alpha,beta,u,ldu,v,ldv,q,ldq,work,ncycle,info) CNAME(ctgsja)
import
character(len=1)::jobu
character(len=1)::jobv
character(len=1)::jobq
integer(blas77_int)::m
integer(blas77_int)::p
integer(blas77_int)::n
integer(blas77_int)::k
integer(blas77_int)::l
integer(blas77_int)::lda
complex(blas77_f32)::a(lda,*)
integer(blas77_int)::ldb
complex(blas77_f32)::b(ldb,*)
real(blas77_f32)::tola
real(blas77_f32)::tolb
real(blas77_f32)::alpha(*)
real(blas77_f32)::beta(*)
integer(blas77_int)::ldu
complex(blas77_f32)::u(ldu,*)
integer(blas77_int)::ldv
complex(blas77_f32)::v(ldv,*)
integer(blas77_int)::ldq
complex(blas77_f32)::q(ldq,*)
complex(blas77_f32)::work(*)
integer(blas77_int)::ncycle
integer(blas77_int)::info
end
