subroutine dgedmdq(jobs,jobz,jobr,jobq,jobt,jobf,whtsvd,m,n,f,ldf,x,ldx,y,ldy,nrnk,tol,k,reig,imeig,z,ldz,res,b,ldb,v,ldv,s,lds,work,lwork,iwork,liwork,info) CNAME(dgedmdq)
import
character(len=1),intent(in)::jobs
character(len=1),intent(in)::jobz
character(len=1),intent(in)::jobr
character(len=1),intent(in)::jobq
character(len=1),intent(in)::jobt
character(len=1),intent(in)::jobf
integer(blas77_int),intent(in)::whtsvd
integer(blas77_int),intent(in)::m
integer(blas77_int),intent(in)::n
integer(blas77_int),intent(in)::ldf
real(blas77_f64),intent(inout)::f(ldf,*)
integer(blas77_int),intent(in)::ldx
real(blas77_f64),intent(out)::x(ldx,*)
integer(blas77_int),intent(in)::ldy
real(blas77_f64),intent(out)::y(ldy,*)
integer(blas77_int),intent(in)::nrnk
real(blas77_f64),intent(in)::tol
integer(blas77_int),intent(out)::k
real(blas77_f64),intent(out)::reig(*)
real(blas77_f64),intent(out)::imeig(*)
integer(blas77_int),intent(in)::ldz
real(blas77_f64),intent(out)::z(ldz,*)
real(blas77_f64),intent(out)::res(*)
integer(blas77_int),intent(in)::ldb
real(blas77_f64),intent(out)::b(ldb,*)
integer(blas77_int),intent(in)::ldv
real(blas77_f64),intent(out)::v(ldv,*)
integer(blas77_int),intent(in)::lds
real(blas77_f64),intent(out)::s(lds,*)
real(blas77_f64),intent(out)::work(*)
integer(blas77_int),intent(in)::lwork
integer(blas77_int),intent(out)::iwork(*)
integer(blas77_int),intent(in)::liwork
integer(blas77_int),intent(out)::info
end
