subroutine dgeesx(jobvs,sort,select,sense,n,a,lda,sdim,wr,wi,vs,ldvs,rconde,rcondv,work,lwork,iwork,liwork,bwork,info) CNAME(dgeesx)
import
character(len=1)::jobvs
character(len=1)::sort
procedure(logical)::select
character(len=1)::sense
integer(blas77_int)::n
integer(blas77_int)::lda
real(blas77_f64)::a(lda,*)
integer(blas77_int)::sdim
real(blas77_f64)::wr(*)
real(blas77_f64)::wi(*)
integer(blas77_int)::ldvs
real(blas77_f64)::vs(ldvs,*)
real(blas77_f64)::rconde
real(blas77_f64)::rcondv
real(blas77_f64)::work(*)
integer(blas77_int)::lwork
integer(blas77_int)::iwork(*)
integer(blas77_int)::liwork
logical::bwork(*)
integer(blas77_int)::info
end
