subroutine dggesx(jobvsl,jobvsr,sort,selctg,sense,n,a,lda,b,ldb,sdim,alphar,alphai,beta,vsl,ldvsl,vsr,ldvsr,rconde,rcondv,work,lwork,iwork,liwork,bwork,info) CNAME(dggesx)
import
character(len=1)::jobvsl
character(len=1)::jobvsr
character(len=1)::sort
procedure(logical)::selctg
character(len=1)::sense
integer(blas77_int)::n
integer(blas77_int)::lda
real(blas77_f64)::a(lda,*)
integer(blas77_int)::ldb
real(blas77_f64)::b(ldb,*)
integer(blas77_int)::sdim
real(blas77_f64)::alphar(*)
real(blas77_f64)::alphai(*)
real(blas77_f64)::beta(*)
integer(blas77_int)::ldvsl
real(blas77_f64)::vsl(ldvsl,*)
integer(blas77_int)::ldvsr
real(blas77_f64)::vsr(ldvsr,*)
real(blas77_f64)::rconde(2)
real(blas77_f64)::rcondv(2)
real(blas77_f64)::work(*)
integer(blas77_int)::lwork
integer(blas77_int)::iwork(*)
integer(blas77_int)::liwork
logical::bwork(*)
integer(blas77_int)::info
end
