subroutine dggev(jobvl,jobvr,n,a,lda,b,ldb,alphar,alphai,beta,vl,ldvl,vr,ldvr,work,lwork,info) CNAME(dggev)
import
character(len=1)::jobvl
character(len=1)::jobvr
integer(blas77_int)::n
integer(blas77_int)::lda
real(blas77_f64)::a(lda,*)
integer(blas77_int)::ldb
real(blas77_f64)::b(ldb,*)
real(blas77_f64)::alphar(*)
real(blas77_f64)::alphai(*)
real(blas77_f64)::beta(*)
integer(blas77_int)::ldvl
real(blas77_f64)::vl(ldvl,*)
integer(blas77_int)::ldvr
real(blas77_f64)::vr(ldvr,*)
real(blas77_f64)::work(*)
integer(blas77_int)::lwork
integer(blas77_int)::info
end
