subroutine dggevx(balanc,jobvl,jobvr,sense,n,a,lda,b,ldb,alphar,alphai,beta,vl,ldvl,vr,ldvr,ilo,ihi,lscale,rscale,abnrm,bbnrm,rconde,rcondv,work,lwork,iwork,bwork,info) CNAME(dggevx)
import
character(len=1)::balanc
character(len=1)::jobvl
character(len=1)::jobvr
character(len=1)::sense
integer(blas77_int)::n
integer(blas77_int)::lda
real(blas77_f64)::a(lda,*)
integer(blas77_int)::ldb
real(blas77_f64)::b(ldb,*)
real(blas77_f64)::alphar(*)
real(blas77_f64)::alphai(*)
real(blas77_f64)::beta(*)
integer(blas77_int)::ldvl
real(blas77_f64)::vl(ldvl,*)
integer(blas77_int)::ldvr
real(blas77_f64)::vr(ldvr,*)
integer(blas77_int)::ilo
integer(blas77_int)::ihi
real(blas77_f64)::lscale(*)
real(blas77_f64)::rscale(*)
real(blas77_f64)::abnrm
real(blas77_f64)::bbnrm
real(blas77_f64)::rconde(*)
real(blas77_f64)::rcondv(*)
real(blas77_f64)::work(*)
integer(blas77_int)::lwork
integer(blas77_int)::iwork(*)
logical::bwork(*)
integer(blas77_int)::info
end
