subroutine dlaed8(icompq,k,n,qsiz,d,q,ldq,indxq,rho,cutpnt,z,dlambda,q2,ldq2,w,perm,givptr,givcol,givnum,indxp,indx,info) CNAME(dlaed8)
import
integer(blas77_int)::icompq
integer(blas77_int)::k
integer(blas77_int)::n
integer(blas77_int)::qsiz
real(blas77_f64)::d(*)
integer(blas77_int)::ldq
real(blas77_f64)::q(ldq,*)
integer(blas77_int)::indxq(*)
real(blas77_f64)::rho
integer(blas77_int)::cutpnt
real(blas77_f64)::z(*)
real(blas77_f64)::dlambda(*)
integer(blas77_int)::ldq2
real(blas77_f64)::q2(ldq2,*)
real(blas77_f64)::w(*)
integer(blas77_int)::perm(*)
integer(blas77_int)::givptr
integer(blas77_int)::givcol(2,*)
real(blas77_f64)::givnum(2,*)
integer(blas77_int)::indxp(*)
integer(blas77_int)::indx(*)
integer(blas77_int)::info
end
