subroutine dlaed2(k,n,n1,d,q,ldq,indxq,rho,z,dlambda,w,q2,indx,indxc,indxp,coltyp,info) CNAME(dlaed2)
import
integer(blas77_int)::k
integer(blas77_int)::n
integer(blas77_int)::n1
real(blas77_f64)::d(*)
integer(blas77_int)::ldq
real(blas77_f64)::q(ldq,*)
integer(blas77_int)::indxq(*)
real(blas77_f64)::rho
real(blas77_f64)::z(*)
real(blas77_f64)::dlambda(*)
real(blas77_f64)::w(*)
real(blas77_f64)::q2(*)
integer(blas77_int)::indx(*)
integer(blas77_int)::indxc(*)
integer(blas77_int)::indxp(*)
integer(blas77_int)::coltyp(*)
integer(blas77_int)::info
end
