subroutine dlaebz(ijob,nitmax,n,mmax,minp,nbmin,abstol,reltol,pivmin,d,e,e2,nval,ab,c,mout,nab,work,iwork,info) CNAME(dlaebz)
import
integer(blas77_int)::ijob
integer(blas77_int)::nitmax
integer(blas77_int)::n
integer(blas77_int)::mmax
integer(blas77_int)::minp
integer(blas77_int)::nbmin
real(blas77_f64)::abstol
real(blas77_f64)::reltol
real(blas77_f64)::pivmin
real(blas77_f64)::d(*)
real(blas77_f64)::e(*)
real(blas77_f64)::e2(*)
integer(blas77_int)::nval(*)
real(blas77_f64)::ab(mmax,*)
real(blas77_f64)::c(*)
integer(blas77_int)::mout
integer(blas77_int)::nab(mmax,*)
real(blas77_f64)::work(*)
integer(blas77_int)::iwork(*)
integer(blas77_int)::info
end
