recursive subroutine dlaqz0(wants,wantq,wantz,n,ilo,ihi,a,lda,b,ldb,alphar,alphai,beta,q,ldq,z,ldz,work,lwork,rec,info) CNAME(dlaqz0)
import
character(len=1),intent(in)::wants
character(len=1),intent(in)::wantq
character(len=1),intent(in)::wantz
integer(blas77_int),intent(in)::n
integer(blas77_int),intent(in)::ilo
integer(blas77_int),intent(in)::ihi
integer(blas77_int),intent(in)::lda
real(blas77_f64),intent(inout)::a(lda,*)
integer(blas77_int),intent(in)::ldb
real(blas77_f64),intent(inout)::b(ldb,*)
real(blas77_f64),intent(inout)::alphar(*)
real(blas77_f64),intent(inout)::alphai(*)
real(blas77_f64),intent(inout)::beta(*)
integer(blas77_int),intent(in)::ldq
real(blas77_f64),intent(inout)::q(ldq,*)
integer(blas77_int),intent(in)::ldz
real(blas77_f64),intent(inout)::z(ldz,*)
real(blas77_f64),intent(inout)::work(*)
integer(blas77_int),intent(in)::lwork
integer(blas77_int),intent(in)::rec
integer(blas77_int),intent(out)::info
end
