subroutine dlaqz4(ilschur,ilq,ilz,n,ilo,ihi,nshifts,nblock_desired,sr,si,ss,a,lda,b,ldb,q,ldq,z,ldz,qc,ldqc,zc,ldzc,work,lwork,info) CNAME(dlaqz4)
import
logical,intent(in)::ilschur
logical,intent(in)::ilq
logical,intent(in)::ilz
integer(blas77_int),intent(in)::n
integer(blas77_int),intent(in)::ilo
integer(blas77_int),intent(in)::ihi
integer(blas77_int),intent(in)::nshifts
integer(blas77_int),intent(in)::nblock_desired
real(blas77_f64),intent(inout)::sr(*)
real(blas77_f64),intent(inout)::si(*)
real(blas77_f64),intent(inout)::ss(*)
integer(blas77_int),intent(in)::lda
real(blas77_f64),intent(inout)::a(lda,*)
integer(blas77_int),intent(in)::ldb
real(blas77_f64),intent(inout)::b(ldb,*)
integer(blas77_int),intent(in)::ldq
real(blas77_f64),intent(inout)::q(ldq,*)
integer(blas77_int),intent(in)::ldz
real(blas77_f64),intent(inout)::z(ldz,*)
integer(blas77_int),intent(in)::ldqc
real(blas77_f64),intent(inout)::qc(ldqc,*)
integer(blas77_int),intent(in)::ldzc
real(blas77_f64),intent(inout)::zc(ldzc,*)
real(blas77_f64),intent(inout)::work(*)
integer(blas77_int),intent(in)::lwork
integer(blas77_int),intent(out)::info
end
