subroutine dlarrd(range,order,n,vl,vu,il,iu,gers,reltol,d,e,e2,pivmin,nsplit,isplit,m,w,werr,wl,wu,iblock,indexw,work,iwork,info) CNAME(dlarrd)
import
character(len=1)::range
character(len=1)::order
integer(blas77_int)::n
real(blas77_f64)::vl
real(blas77_f64)::vu
integer(blas77_int)::il
integer(blas77_int)::iu
real(blas77_f64)::gers(*)
real(blas77_f64)::reltol
real(blas77_f64)::d(*)
real(blas77_f64)::e(*)
real(blas77_f64)::e2(*)
real(blas77_f64)::pivmin
integer(blas77_int)::nsplit
integer(blas77_int)::isplit(*)
integer(blas77_int)::m
real(blas77_f64)::w(*)
real(blas77_f64)::werr(*)
real(blas77_f64)::wl
real(blas77_f64)::wu
integer(blas77_int)::iblock(*)
integer(blas77_int)::indexw(*)
real(blas77_f64)::work(*)
integer(blas77_int)::iwork(*)
integer(blas77_int)::info
end
