subroutine dlasd6(icompq,nl,nr,sqre,d,vf,vl,alpha,beta,idxq,perm,givptr,givcol,ldgcol,givnum,ldgnum,poles,difl,difr,z,k,c,s,work,iwork,info) CNAME(dlasd6)
import
integer(blas77_int)::icompq
integer(blas77_int)::nl
integer(blas77_int)::nr
integer(blas77_int)::sqre
real(blas77_f64)::d(*)
real(blas77_f64)::vf(*)
real(blas77_f64)::vl(*)
real(blas77_f64)::alpha
real(blas77_f64)::beta
integer(blas77_int)::idxq(*)
integer(blas77_int)::perm(*)
integer(blas77_int)::givptr
integer(blas77_int)::ldgcol
integer(blas77_int)::givcol(ldgcol,*)
integer(blas77_int)::ldgnum
real(blas77_f64)::givnum(ldgnum,*)
real(blas77_f64)::poles(ldgnum,*)
real(blas77_f64)::difl(*)
real(blas77_f64)::difr(*)
real(blas77_f64)::z(*)
integer(blas77_int)::k
real(blas77_f64)::c
real(blas77_f64)::s
real(blas77_f64)::work(*)
integer(blas77_int)::iwork(*)
integer(blas77_int)::info
end
