subroutine dlasd7(icompq,nl,nr,sqre,k,d,z,zw,vf,vfw,vl,vlw,alpha,beta,dsigma,idx,idxp,idxq,perm,givptr,givcol,ldgcol,givnum,ldgnum,c,s,info) CNAME(dlasd7)
import
integer(blas77_int)::icompq
integer(blas77_int)::nl
integer(blas77_int)::nr
integer(blas77_int)::sqre
integer(blas77_int)::k
real(blas77_f64)::d(*)
real(blas77_f64)::z(*)
real(blas77_f64)::zw(*)
real(blas77_f64)::vf(*)
real(blas77_f64)::vfw(*)
real(blas77_f64)::vl(*)
real(blas77_f64)::vlw(*)
real(blas77_f64)::alpha
real(blas77_f64)::beta
real(blas77_f64)::dsigma(*)
integer(blas77_int)::idx(*)
integer(blas77_int)::idxp(*)
integer(blas77_int)::idxq(*)
integer(blas77_int)::perm(*)
integer(blas77_int)::givptr
integer(blas77_int)::ldgcol
integer(blas77_int)::givcol(ldgcol,*)
integer(blas77_int)::ldgnum
real(blas77_f64)::givnum(ldgnum,*)
real(blas77_f64)::c
real(blas77_f64)::s
integer(blas77_int)::info
end
