subroutine dtgsen(ijob,wantq,wantz,select,n,a,lda,b,ldb,alphar,alphai,beta,q,ldq,z,ldz,m,pl,pr,dif,work,lwork,iwork,liwork,info) CNAME(dtgsen)
import
integer(blas77_int)::ijob
logical::wantq
logical::wantz
logical::select(*)
integer(blas77_int)::n
integer(blas77_int)::lda
real(blas77_f64)::a(lda,*)
integer(blas77_int)::ldb
real(blas77_f64)::b(ldb,*)
real(blas77_f64)::alphar(*)
real(blas77_f64)::alphai(*)
real(blas77_f64)::beta(*)
integer(blas77_int)::ldq
real(blas77_f64)::q(ldq,*)
integer(blas77_int)::ldz
real(blas77_f64)::z(ldz,*)
integer(blas77_int)::m
real(blas77_f64)::pl
real(blas77_f64)::pr
real(blas77_f64)::dif(*)
real(blas77_f64)::work(*)
integer(blas77_int)::lwork
integer(blas77_int)::iwork(*)
integer(blas77_int)::liwork
integer(blas77_int)::info
end
