subroutine dtprfb(side,trans,direct,storev,m,n,k,l,v,ldv,t,ldt,a,lda,b,ldb,work,ldwork) CNAME(dtprfb)
import
character(len=1)::side
character(len=1)::trans
character(len=1)::direct
character(len=1)::storev
integer(blas77_int)::m
integer(blas77_int)::n
integer(blas77_int)::k
integer(blas77_int)::l
integer(blas77_int)::ldv
real(blas77_f64)::v(ldv,*)
integer(blas77_int)::ldt
real(blas77_f64)::t(ldt,*)
integer(blas77_int)::lda
real(blas77_f64)::a(lda,*)
integer(blas77_int)::ldb
real(blas77_f64)::b(ldb,*)
integer(blas77_int)::ldwork
real(blas77_f64)::work(ldwork,*)
end
