subroutine dtrsna(job,howmny,select,n,t,ldt,vl,ldvl,vr,ldvr,s,sep,mm,m,work,ldwork,iwork,info) CNAME(dtrsna)
import
character(len=1)::job
character(len=1)::howmny
logical::select(*)
integer(blas77_int)::n
integer(blas77_int)::ldt
real(blas77_f64)::t(ldt,*)
integer(blas77_int)::ldvl
real(blas77_f64)::vl(ldvl,*)
integer(blas77_int)::ldvr
real(blas77_f64)::vr(ldvr,*)
real(blas77_f64)::s(*)
real(blas77_f64)::sep(*)
integer(blas77_int)::mm
integer(blas77_int)::m
integer(blas77_int)::ldwork
real(blas77_f64)::work(ldwork,*)
integer(blas77_int)::iwork(*)
integer(blas77_int)::info
end
