subroutine sgbsvxx(fact,trans,n,kl,ku,nrhs,ab,ldab,afb,ldafb,ipiv,equed,r,c,b,ldb,x,ldx,rcond,rpvgrw,berr,n_err_bnds,err_bnds_norm,err_bnds_comp,nparams,params,work,iwork,info) CNAME(sgbsvxx)
import
character(len=1)::fact
character(len=1)::trans
integer(blas77_int)::n
integer(blas77_int)::kl
integer(blas77_int)::ku
integer(blas77_int)::nrhs
integer(blas77_int)::ldab
real(blas77_f32)::ab(ldab,*)
integer(blas77_int)::ldafb
real(blas77_f32)::afb(ldafb,*)
integer(blas77_int)::ipiv(*)
character(len=1)::equed
real(blas77_f32)::r(*)
real(blas77_f32)::c(*)
integer(blas77_int)::ldb
real(blas77_f32)::b(ldb,*)
integer(blas77_int)::ldx
real(blas77_f32)::x(ldx,*)
real(blas77_f32)::rcond
real(blas77_f32)::rpvgrw
real(blas77_f32)::berr(*)
integer(blas77_int)::n_err_bnds
real(blas77_f32)::err_bnds_norm(nrhs,*)
real(blas77_f32)::err_bnds_comp(nrhs,*)
integer(blas77_int)::nparams
real(blas77_f32)::params(*)
real(blas77_f32)::work(*)
integer(blas77_int)::iwork(*)
integer(blas77_int)::info
end
