subroutine sgejsv(joba,jobu,jobv,jobr,jobt,jobp,m,n,a,lda,sva,u,ldu,v,ldv,work,lwork,iwork,info) CNAME(sgejsv)
import
character(len=1)::joba
character(len=1)::jobu
character(len=1)::jobv
character(len=1)::jobr
character(len=1)::jobt
character(len=1)::jobp
integer(blas77_int)::m
integer(blas77_int)::n
integer(blas77_int)::lda
real(blas77_f32)::a(lda,*)
real(blas77_f32)::sva(n)
integer(blas77_int)::ldu
real(blas77_f32)::u(ldu,*)
integer(blas77_int)::ldv
real(blas77_f32)::v(ldv,*)
integer(blas77_int)::lwork
real(blas77_f32)::work(lwork)
integer(blas77_int)::iwork(*)
integer(blas77_int)::info
end
