subroutine sla_gerfsx_extended(prec_type,trans_type,n,nrhs,a,lda,af,ldaf,ipiv,colequ,c,b,ldb,y,ldy,berr_out,n_norms,errs_n,errs_c,res,ayb,dy,y_tail,rcond,ithresh,rthresh,dz_ub,ignore_cwise,info) CNAME(sla_gerfsx_extended)
import
integer(blas77_int)::prec_type
integer(blas77_int)::trans_type
integer(blas77_int)::n
integer(blas77_int)::nrhs
integer(blas77_int)::lda
real(blas77_f32)::a(lda,*)
integer(blas77_int)::ldaf
real(blas77_f32)::af(ldaf,*)
integer(blas77_int)::ipiv(*)
logical::colequ
real(blas77_f32)::c(*)
integer(blas77_int)::ldb
real(blas77_f32)::b(ldb,*)
integer(blas77_int)::ldy
real(blas77_f32)::y(ldy,*)
real(blas77_f32)::berr_out(*)
integer(blas77_int)::n_norms
real(blas77_f32)::errs_n(nrhs,*)
real(blas77_f32)::errs_c(nrhs,*)
real(blas77_f32)::res(*)
real(blas77_f32)::ayb(*)
real(blas77_f32)::dy(*)
real(blas77_f32)::y_tail(*)
real(blas77_f32)::rcond
integer(blas77_int)::ithresh
real(blas77_f32)::rthresh
real(blas77_f32)::dz_ub
logical::ignore_cwise
integer(blas77_int)::info
end
