subroutine sla_porfsx_extended(prec_type,uplo,n,nrhs,a,lda,af,ldaf,colequ,c,b,ldb,y,ldy,berr_out,n_norms,err_bnds_norm,err_bnds_comp,res,ayb,dy,y_tail,rcond,ithresh,rthresh,dz_ub,ignore_cwise,info) CNAME(sla_porfsx_extended)
import
integer(blas77_int)::prec_type
character(len=1)::uplo
integer(blas77_int)::n
integer(blas77_int)::nrhs
integer(blas77_int)::lda
real(blas77_f32)::a(lda,*)
integer(blas77_int)::ldaf
real(blas77_f32)::af(ldaf,*)
logical::colequ
real(blas77_f32)::c(*)
integer(blas77_int)::ldb
real(blas77_f32)::b(ldb,*)
integer(blas77_int)::ldy
real(blas77_f32)::y(ldy,*)
real(blas77_f32)::berr_out(*)
integer(blas77_int)::n_norms
real(blas77_f32)::err_bnds_norm(nrhs,*)
real(blas77_f32)::err_bnds_comp(nrhs,*)
real(blas77_f32)::res(*)
real(blas77_f32)::ayb(*)
real(blas77_f32)::dy(*)
real(blas77_f32)::y_tail(*)
real(blas77_f32)::rcond
integer(blas77_int)::ithresh
real(blas77_f32)::rthresh
real(blas77_f32)::dz_ub
logical::ignore_cwise
integer(blas77_int)::info
end
