subroutine slaed2(k,n,n1,d,q,ldq,indxq,rho,z,dlambda,w,q2,indx,indxc,indxp,coltyp,info) CNAME(slaed2)
import
integer(blas77_int)::k
integer(blas77_int)::n
integer(blas77_int)::n1
real(blas77_f32)::d(*)
integer(blas77_int)::ldq
real(blas77_f32)::q(ldq,*)
integer(blas77_int)::indxq(*)
real(blas77_f32)::rho
real(blas77_f32)::z(*)
real(blas77_f32)::dlambda(*)
real(blas77_f32)::w(*)
real(blas77_f32)::q2(*)
integer(blas77_int)::indx(*)
integer(blas77_int)::indxc(*)
integer(blas77_int)::indxp(*)
integer(blas77_int)::coltyp(*)
integer(blas77_int)::info
end
