recursive subroutine slaqz3(ilschur,ilq,ilz,n,ilo,ihi,nw,a,lda,b,ldb,q,ldq,z,ldz,ns,nd,alphar,alphai,beta,qc,ldqc,zc,ldzc,work,lwork,rec,info) CNAME(slaqz3)
import
logical,intent(in)::ilschur
logical,intent(in)::ilq
logical,intent(in)::ilz
integer(blas77_int),intent(in)::n
integer(blas77_int),intent(in)::ilo
integer(blas77_int),intent(in)::ihi
integer(blas77_int),intent(in)::nw
integer(blas77_int),intent(in)::lda
real(blas77_f32),intent(inout)::a(lda,*)
integer(blas77_int),intent(in)::ldb
real(blas77_f32),intent(inout)::b(ldb,*)
integer(blas77_int),intent(in)::ldq
real(blas77_f32),intent(inout)::q(ldq,*)
integer(blas77_int),intent(in)::ldz
real(blas77_f32),intent(inout)::z(ldz,*)
integer(blas77_int),intent(out)::ns
integer(blas77_int),intent(out)::nd
real(blas77_f32),intent(inout)::alphar(*)
real(blas77_f32),intent(inout)::alphai(*)
real(blas77_f32),intent(inout)::beta(*)
integer(blas77_int),intent(in)::ldqc
real(blas77_f32)::qc(ldqc,*)
integer(blas77_int),intent(in)::ldzc
real(blas77_f32)::zc(ldzc,*)
real(blas77_f32)::work(*)
integer(blas77_int),intent(in)::lwork
integer(blas77_int),intent(in)::rec
integer(blas77_int),intent(out)::info
end
