subroutine slarrd(range,order,n,vl,vu,il,iu,gers,reltol,d,e,e2,pivmin,nsplit,isplit,m,w,werr,wl,wu,iblock,indexw,work,iwork,info) CNAME(slarrd)
import
character(len=1)::range
character(len=1)::order
integer(blas77_int)::n
real(blas77_f32)::vl
real(blas77_f32)::vu
integer(blas77_int)::il
integer(blas77_int)::iu
real(blas77_f32)::gers(*)
real(blas77_f32)::reltol
real(blas77_f32)::d(*)
real(blas77_f32)::e(*)
real(blas77_f32)::e2(*)
real(blas77_f32)::pivmin
integer(blas77_int)::nsplit
integer(blas77_int)::isplit(*)
integer(blas77_int)::m
real(blas77_f32)::w(*)
real(blas77_f32)::werr(*)
real(blas77_f32)::wl
real(blas77_f32)::wu
integer(blas77_int)::iblock(*)
integer(blas77_int)::indexw(*)
real(blas77_f32)::work(*)
integer(blas77_int)::iwork(*)
integer(blas77_int)::info
end
