subroutine slasd7(icompq,nl,nr,sqre,k,d,z,zw,vf,vfw,vl,vlw,alpha,beta,dsigma,idx,idxp,idxq,perm,givptr,givcol,ldgcol,givnum,ldgnum,c,s,info) CNAME(slasd7)
import
integer(blas77_int)::icompq
integer(blas77_int)::nl
integer(blas77_int)::nr
integer(blas77_int)::sqre
integer(blas77_int)::k
real(blas77_f32)::d(*)
real(blas77_f32)::z(*)
real(blas77_f32)::zw(*)
real(blas77_f32)::vf(*)
real(blas77_f32)::vfw(*)
real(blas77_f32)::vl(*)
real(blas77_f32)::vlw(*)
real(blas77_f32)::alpha
real(blas77_f32)::beta
real(blas77_f32)::dsigma(*)
integer(blas77_int)::idx(*)
integer(blas77_int)::idxp(*)
integer(blas77_int)::idxq(*)
integer(blas77_int)::perm(*)
integer(blas77_int)::givptr
integer(blas77_int)::ldgcol
integer(blas77_int)::givcol(ldgcol,*)
integer(blas77_int)::ldgnum
real(blas77_f32)::givnum(ldgnum,*)
real(blas77_f32)::c
real(blas77_f32)::s
integer(blas77_int)::info
end
