subroutine slasd6(icompq,nl,nr,sqre,d,vf,vl,alpha,beta,idxq,perm,givptr,givcol,ldgcol,givnum,ldgnum,poles,difl,difr,z,k,c,s,work,iwork,info) CNAME(slasd6)
import
integer(blas77_int)::icompq
integer(blas77_int)::nl
integer(blas77_int)::nr
integer(blas77_int)::sqre
real(blas77_f32)::d(*)
real(blas77_f32)::vf(*)
real(blas77_f32)::vl(*)
real(blas77_f32)::alpha
real(blas77_f32)::beta
integer(blas77_int)::idxq(*)
integer(blas77_int)::perm(*)
integer(blas77_int)::givptr
integer(blas77_int)::ldgcol
integer(blas77_int)::givcol(ldgcol,*)
integer(blas77_int)::ldgnum
real(blas77_f32)::givnum(ldgnum,*)
real(blas77_f32)::poles(ldgnum,*)
real(blas77_f32)::difl(*)
real(blas77_f32)::difr(*)
real(blas77_f32)::z(*)
integer(blas77_int)::k
real(blas77_f32)::c
real(blas77_f32)::s
real(blas77_f32)::work(*)
integer(blas77_int)::iwork(*)
integer(blas77_int)::info
end
