subroutine stgexc(wantq,wantz,n,a,lda,b,ldb,q,ldq,z,ldz,ifst,ilst,work,lwork,info) CNAME(stgexc)
import
logical::wantq
logical::wantz
integer(blas77_int)::n
integer(blas77_int)::lda
real(blas77_f32)::a(lda,*)
integer(blas77_int)::ldb
real(blas77_f32)::b(ldb,*)
integer(blas77_int)::ldq
real(blas77_f32)::q(ldq,*)
integer(blas77_int)::ldz
real(blas77_f32)::z(ldz,*)
integer(blas77_int)::ifst
integer(blas77_int)::ilst
real(blas77_f32)::work(*)
integer(blas77_int)::lwork
integer(blas77_int)::info
end
