subroutine stgsyl(trans,ijob,m,n,a,lda,b,ldb,c,ldc,d,ldd,e,lde,f,ldf,scale,dif,work,lwork,iwork,info) CNAME(stgsyl)
import
character(len=1)::trans
integer(blas77_int)::ijob
integer(blas77_int)::m
integer(blas77_int)::n
integer(blas77_int)::lda
real(blas77_f32)::a(lda,*)
integer(blas77_int)::ldb
real(blas77_f32)::b(ldb,*)
integer(blas77_int)::ldc
real(blas77_f32)::c(ldc,*)
integer(blas77_int)::ldd
real(blas77_f32)::d(ldd,*)
integer(blas77_int)::lde
real(blas77_f32)::e(lde,*)
integer(blas77_int)::ldf
real(blas77_f32)::f(ldf,*)
real(blas77_f32)::scale
real(blas77_f32)::dif
real(blas77_f32)::work(*)
integer(blas77_int)::lwork
integer(blas77_int)::iwork(*)
integer(blas77_int)::info
end
