subroutine zgbsvxx(fact,trans,n,kl,ku,nrhs,ab,ldab,afb,ldafb,ipiv,equed,r,c,b,ldb,x,ldx,rcond,rpvgrw,berr,n_err_bnds,err_bnds_norm,err_bnds_comp,nparams,params,work,rwork,info) CNAME(zgbsvxx)
import
character(len=1)::fact
character(len=1)::trans
integer(blas77_int)::n
integer(blas77_int)::kl
integer(blas77_int)::ku
integer(blas77_int)::nrhs
integer(blas77_int)::ldab
complex(blas77_f64)::ab(ldab,*)
integer(blas77_int)::ldafb
complex(blas77_f64)::afb(ldafb,*)
integer(blas77_int)::ipiv(*)
character(len=1)::equed
real(blas77_f64)::r(*)
real(blas77_f64)::c(*)
integer(blas77_int)::ldb
complex(blas77_f64)::b(ldb,*)
integer(blas77_int)::ldx
complex(blas77_f64)::x(ldx,*)
real(blas77_f64)::rcond
real(blas77_f64)::rpvgrw
real(blas77_f64)::berr(*)
integer(blas77_int)::n_err_bnds
real(blas77_f64)::err_bnds_norm(nrhs,*)
real(blas77_f64)::err_bnds_comp(nrhs,*)
integer(blas77_int)::nparams
real(blas77_f64)::params(*)
complex(blas77_f64)::work(*)
real(blas77_f64)::rwork(*)
integer(blas77_int)::info
end
