subroutine zherfsx(uplo,equed,n,nrhs,a,lda,af,ldaf,ipiv,s,b,ldb,x,ldx,rcond,berr,n_err_bnds,err_bnds_norm,err_bnds_comp,nparams,params,work,rwork,info) CNAME(zherfsx)
import
character(len=1)::uplo
character(len=1)::equed
integer(blas77_int)::n
integer(blas77_int)::nrhs
integer(blas77_int)::lda
complex(blas77_f64)::a(lda,*)
integer(blas77_int)::ldaf
complex(blas77_f64)::af(ldaf,*)
integer(blas77_int)::ipiv(*)
real(blas77_f64)::s(*)
integer(blas77_int)::ldb
complex(blas77_f64)::b(ldb,*)
integer(blas77_int)::ldx
complex(blas77_f64)::x(ldx,*)
real(blas77_f64)::rcond
real(blas77_f64)::berr(*)
integer(blas77_int)::n_err_bnds
real(blas77_f64)::err_bnds_norm(nrhs,*)
real(blas77_f64)::err_bnds_comp(nrhs,*)
integer(blas77_int)::nparams
real(blas77_f64)::params(*)
complex(blas77_f64)::work(*)
real(blas77_f64)::rwork(*)
integer(blas77_int)::info
end
