subroutine zhpsvx(fact,uplo,n,nrhs,ap,afp,ipiv,b,ldb,x,ldx,rcond,ferr,berr,work,rwork,info) CNAME(zhpsvx)
import
character(len=1)::fact
character(len=1)::uplo
integer(blas77_int)::n
integer(blas77_int)::nrhs
complex(blas77_f64)::ap(*)
complex(blas77_f64)::afp(*)
integer(blas77_int)::ipiv(*)
integer(blas77_int)::ldb
complex(blas77_f64)::b(ldb,*)
integer(blas77_int)::ldx
complex(blas77_f64)::x(ldx,*)
real(blas77_f64)::rcond
real(blas77_f64)::ferr(*)
real(blas77_f64)::berr(*)
complex(blas77_f64)::work(*)
real(blas77_f64)::rwork(*)
integer(blas77_int)::info
end
