subroutine zhsein(side,eigsrc,initv,select,n,h,ldh,w,vl,ldvl,vr,ldvr,mm,m,work,rwork,ifaill,ifailr,info) CNAME(zhsein)
import
character(len=1)::side
character(len=1)::eigsrc
character(len=1)::initv
logical::select(*)
integer(blas77_int)::n
integer(blas77_int)::ldh
complex(blas77_f64)::h(ldh,*)
complex(blas77_f64)::w(*)
integer(blas77_int)::ldvl
complex(blas77_f64)::vl(ldvl,*)
integer(blas77_int)::ldvr
complex(blas77_f64)::vr(ldvr,*)
integer(blas77_int)::mm
integer(blas77_int)::m
complex(blas77_f64)::work(*)
real(blas77_f64)::rwork(*)
integer(blas77_int)::ifaill(*)
integer(blas77_int)::ifailr(*)
integer(blas77_int)::info
end
