subroutine zla_gerfsx_extended(prec_type,trans_type,n,nrhs,a,lda,af,ldaf,ipiv,colequ,c,b,ldb,y,ldy,berr_out,n_norms,errs_n,errs_c,res,ayb,dy,y_tail,rcond,ithresh,rthresh,dz_ub,ignore_cwise,info) CNAME(zla_gerfsx_extended)
import
integer(blas77_int)::prec_type
integer(blas77_int)::trans_type
integer(blas77_int)::n
integer(blas77_int)::nrhs
integer(blas77_int)::lda
complex(blas77_f64)::a(lda,*)
integer(blas77_int)::ldaf
complex(blas77_f64)::af(ldaf,*)
integer(blas77_int)::ipiv(*)
logical::colequ
real(blas77_f64)::c(*)
integer(blas77_int)::ldb
complex(blas77_f64)::b(ldb,*)
integer(blas77_int)::ldy
complex(blas77_f64)::y(ldy,*)
real(blas77_f64)::berr_out(*)
integer(blas77_int)::n_norms
real(blas77_f64)::errs_n(nrhs,*)
real(blas77_f64)::errs_c(nrhs,*)
complex(blas77_f64)::res(*)
real(blas77_f64)::ayb(*)
complex(blas77_f64)::dy(*)
complex(blas77_f64)::y_tail(*)
real(blas77_f64)::rcond
integer(blas77_int)::ithresh
real(blas77_f64)::rthresh
real(blas77_f64)::dz_ub
logical::ignore_cwise
integer(blas77_int)::info
end
