subroutine zlals0(icompq,nl,nr,sqre,nrhs,b,ldb,bx,ldbx,perm,givptr,givcol,ldgcol,givnum,ldgnum,poles,difl,difr,z,k,c,s,rwork,info) CNAME(zlals0)
import
integer(blas77_int)::icompq
integer(blas77_int)::nl
integer(blas77_int)::nr
integer(blas77_int)::sqre
integer(blas77_int)::nrhs
integer(blas77_int)::ldb
complex(blas77_f64)::b(ldb,*)
integer(blas77_int)::ldbx
complex(blas77_f64)::bx(ldbx,*)
integer(blas77_int)::perm(*)
integer(blas77_int)::givptr
integer(blas77_int)::ldgcol
integer(blas77_int)::givcol(ldgcol,*)
integer(blas77_int)::ldgnum
real(blas77_f64)::givnum(ldgnum,*)
real(blas77_f64)::poles(ldgnum,*)
real(blas77_f64)::difl(*)
real(blas77_f64)::difr(ldgnum,*)
real(blas77_f64)::z(*)
integer(blas77_int)::k
real(blas77_f64)::c
real(blas77_f64)::s
real(blas77_f64)::rwork(*)
integer(blas77_int)::info
end
