subroutine zlaqr5(wantt,wantz,kacc22,n,ktop,kbot,nshfts,s,h,ldh,iloz,ihiz,z,ldz,v,ldv,u,ldu,nv,wv,ldwv,nh,wh,ldwh) CNAME(zlaqr5)
import
logical(blas77_int)::wantt
logical(blas77_int)::wantz
integer(blas77_int)::kacc22
integer(blas77_int)::n
integer(blas77_int)::ktop
integer(blas77_int)::kbot
integer(blas77_int)::nshfts
complex(blas77_f64)::s(*)
integer(blas77_int)::ldh
complex(blas77_f64)::h(ldh,*)
integer(blas77_int)::iloz
integer(blas77_int)::ihiz
integer(blas77_int)::ldz
complex(blas77_f64)::z(ldz,*)
integer(blas77_int)::ldv
complex(blas77_f64)::v(ldv,*)
integer(blas77_int)::ldu
complex(blas77_f64)::u(ldu,*)
integer(blas77_int)::nv
integer(blas77_int)::ldwv
complex(blas77_f64)::wv(ldwv,*)
integer(blas77_int)::nh
integer(blas77_int)::ldwh
complex(blas77_f64)::wh(ldwh,*)
end
