pure subroutine zlaqz3(ilschur,ilq,ilz,n,ilo,ihi,nshifts,nblock_desired,alpha, &
    beta,a,lda,b,ldb,q,ldq,z,ldz,qc,ldqc,zc,ldzc,work,lwork,info) &
    BEGCNAME(zlaqz3,SUFFIX)
ENDCNAME(zlaqz3,SUFFIX)
import
logical(blas77_int),intent(in)::ilschur
logical(blas77_int),intent(in)::ilq
logical(blas77_int),intent(in)::ilz
integer(blas77_int),intent(in)::n
integer(blas77_int),intent(in)::ilo
integer(blas77_int),intent(in)::ihi
integer(blas77_int),intent(in)::nshifts
integer(blas77_int),intent(in)::nblock_desired
complex(blas77_f64),intent(inout)::alpha(*)
complex(blas77_f64),intent(inout)::beta(*)
integer(blas77_int),intent(in)::lda
complex(blas77_f64),intent(inout)::a(lda,*)
integer(blas77_int),intent(in)::ldb
complex(blas77_f64),intent(inout)::b(ldb,*)
integer(blas77_int),intent(in)::ldq
complex(blas77_f64),intent(inout)::q(ldq,*)
integer(blas77_int),intent(in)::ldz
complex(blas77_f64),intent(inout)::z(ldz,*)
integer(blas77_int),intent(in)::ldqc
complex(blas77_f64),intent(inout)::qc(ldqc,*)
integer(blas77_int),intent(in)::ldzc
complex(blas77_f64),intent(inout)::zc(ldzc,*)
complex(blas77_f64),intent(inout)::work(*)
integer(blas77_int),intent(in)::lwork
integer(blas77_int),intent(out)::info
end