subroutine zlaqz1(ilq,ilz,k,istartm,istopm,ihi,a,lda,b,ldb,nq,qstart,q,ldq,nz,zstart,z,ldz) CNAME(zlaqz1)
import
logical,intent(in)::ilq
logical,intent(in)::ilz
integer(blas77_int),intent(in)::k
integer(blas77_int),intent(in)::istartm
integer(blas77_int),intent(in)::istopm
integer(blas77_int),intent(in)::ihi
integer(blas77_int),intent(in)::lda
complex(blas77_f64)::a(lda,*)
integer(blas77_int),intent(in)::ldb
complex(blas77_f64)::b(ldb,*)
integer(blas77_int),intent(in)::nq
integer(blas77_int),intent(in)::qstart
integer(blas77_int),intent(in)::ldq
complex(blas77_f64)::q(ldq,*)
integer(blas77_int),intent(in)::nz
integer(blas77_int),intent(in)::zstart
integer(blas77_int),intent(in)::ldz
complex(blas77_f64)::z(ldz,*)
end
