subroutine zstemr(jobz,range,n,d,e,vl,vu,il,iu,m,w,z,ldz,nzc,isuppz,tryrac,work,lwork,iwork,liwork,info) CNAME(zstemr)
import
character(len=1)::jobz
character(len=1)::range
integer(blas77_int)::n
real(blas77_f64)::d(*)
real(blas77_f64)::e(*)
real(blas77_f64)::vl
real(blas77_f64)::vu
integer(blas77_int)::il
integer(blas77_int)::iu
integer(blas77_int)::m
real(blas77_f64)::w(*)
integer(blas77_int)::ldz
complex(blas77_f64)::z(ldz,*)
integer(blas77_int)::nzc
integer(blas77_int)::isuppz(*)
logical::tryrac
real(blas77_f64)::work(*)
integer(blas77_int)::lwork
integer(blas77_int)::iwork(*)
integer(blas77_int)::liwork
integer(blas77_int)::info
end
